function par = initPlotSettings()
    par.showTitle = 0;
    par.box = 1;
    par.grid = 1;
    par.bw = 0;
    par.filterWindowSize = 0;  % Filter over the specified number of episodes
    par.maxEpisodes = -1;      % Control number of episodes plotting is launched
    par.exportFormat = 'pdf';  % Export type
    par.showLegend = 1;
    par.legendPrecise = 1;
    par.legendLocation = 'Best';
    par.legendOrientation = 'vertical'; % vertical, horizontal
    par.fontFamily = 'Courier';
    par.fontSize = 15;
    par.graphsPerPlot = 3;
    par.downsample = 1;
    par.plot = 1;
    par.x_lim = NaN;
    par.y_lim = NaN;
    par.xtick = NaN;
    par.export = 0;
    par.time_indexed = 0;
    par.time_indexed_time = 2;
    par.time_indexed_meas = 3;
    par.time_indexed_timediv = 5;
    par.logx = '';
    par.logy = '';
    par.xlabelformat = '%.f';
    par.ylabelformat = '%.f';
end